### ISSUE TITLE
Can't see the plugin on SonarQube's web interface

### ISSUE THREAD

**Issue by fabervr** [RIGS-IT/sonar-xanitizer#2]
Hi guys and thanks for Xanitizer, it's such a good tool! 
I installed the sonar-xanitizer plugin through SonarQube's Update Center, restarted SonarQube to apply the changes and now I can't see the plugin in the Administration section (so I can't proceed with the configuration). However, I can see that it's installed because it appears in Administration -> System section.
Please can you guys help?

SonarQube version: 6.0, installed via yum as per instruction on http://sonar-pkg.sourceforge.net/
sonar-xanitizer plugin version: 1.3.3, installed via the Update Center.

Thanks!

**Comment by normanwenzel** [comment]
Hi Fabrizio,

my first guess is, that you are in the wrong Administration section. Xanitizer is configured in the project-specific section and not in the global Administration (because the configured XML file is in general for a single project and not for all projects managed by SonarQube).

So please check, that you are looking at the correct Administration section (you have to select the desired project first). Does this solve the problem?

**Comment by fabervr** [comment]
I was indeed in the wrong admin section. 
Thanks for your help responsiveness. Keep up the good work! :)

**Comment by normanwenzel** [comment]
Thank you for the kind words :)
