### ISSUE TITLE
Created 0 issues... but there are Xanitizer findings

### ISSUE THREAD

**Issue by guillermobt** [RIGS-IT/sonar-xanitizer#8]
Hello.

I'm trying to guess the reason why my Findings-List.xml file contains 15 issues but, when passing the file to the sonar-scanner it ends up with no findings :-? 
From the sonar-scanner messages:

> INFO: Reading Xanitizer findings from '/srv/local/tools/sonar/Xanitizer-Findings-List.xml' for project 'Project'
> INFO: Processing Xanitizer analysis results of 2018-02-15 10:40:18
> INFO: Created 0 issues.

I'm running Xanitizer 3.1.4 (Xanitizer-3.1.4-lin64-obf.zip), plugin version 1.5.0 (sonar-xanitizer-plugin-1.5.0.jar), Sonar 6.7 (Community Edition) and sonar-scanner 3.0.3.778 

Any idea why Sonar creates 0 issues when the file *do* contain 15 of them?

**Comment by normanwenzel** [comment]
Hello Guillermo,

there could be several reasons, most of them resulting from the SonarQube guidelines:
- issues detected by Findbugs and OWASP Dependency Check are not migrated (because there are separate SonarQube plugins for these tools and redundant reportings are forbidden)
- issues detected in code that could not be detected/is not present in the context of the SonarQube analysis are not migrated (because each issue must have a corresponding code location). This could happen when the starting point of a path is located in code generated by Xanitizer (for example compiled JSP files or framework simulation code).
- issues that are classified as harmless/informational
- really a bug

If you could provide your output file we can check if the contained issues should be migrated to SonarQube or not.

Many regards
Norman

**Comment by guillermobt** [comment]
Hello Norman.

Thank you for your answer.
I'm attaching the file with the Xanitizer findings (please, rename it with .xml extension)

This is just an example, because this is part of a batch process to be applied to many software projects (most of them are JAVA). I cannot see Xanitizer results in Sonar for any project even when there are many Xanitizer findings for some of them. 
The directory "/backup/" is the root of a code repository containing lots of projects. Each project is inside a subdirectory. 

There are 2 servers:
- Sonar server (6.7) is on a standalone server
- Sonar scanner and Xanitizer are on a different server, where the "/backup" directory containing all the projects to be analyzed resides.

Do you see something anomalous in the file contents?

[Xanitizer-Findings-List.txt](https://github.com/RIGS-IT/sonar-xanitizer/files/1728054/Xanitizer-Findings-List.txt)

**Comment by normanwenzel** [comment]
Hello Guillermo,

it is as expected: 8 of the sample findings are produced by OWASP Dependency check and therefore filtered out. The rest is located in JSP files, which are in general not in the SonarQube context. So no code location could be identified and no issue is created.

So it is expected - but really annoying - behaviour.
Maybe we should provide an additional version of the plugin that is ignoring these restictions and that is not provided via the SonarQube Update Center in the future. But for now, I just can apologize for this and hope for your understanding.

Many regards
Norman

**Comment by guillermobt** [comment]
Hello Norman.
 
Thankyou very much for your help. It was driving me crazy because I was unable to track the reason of the "problem".
If you finally branch to that other version, I would be happy to test it. 

Regards!

**Comment by normanwenzel** [comment]
Fixed with version 2.0
